theme: jekyll-theme-cayman
title: An Introduction to awk
description: This page is a step-by-step walk-thru of the awk programming language. It assumes zero knowledge of awk itself, but some basic knowledge of programming languages and the command line.